# Generated by Django 5.1.6 on 2025-02-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, default='1hTO0v', max_length=10, unique=True)),
                ('long_url', models.URLField()),
                ('visit_count', models.IntegerField(default=0)),
            ],
        ),
    ]
